Repository Ureca-miniproject2/siso-balance-game, pull requests merged in 2024-09, with the labels that each got.

#2 feat: Header 추가
  frontend/src/components/common/icon/HamburgerIcon.jsx
  frontend/src/components/header/Header.jsx
  frontend/src/components/header/Header.styled.js
  frontend/src/layout/GlobalLayout.jsx
  frontend/src/layout/GlobalLayout.styled.js
Labels: 🎨 프론트엔드, ✏️ 기능

#1 feat:item레이이웃저장
  frontend/src/components/item/Item.jsx
  frontend/src/components/item/Item.styled.js
  frontend/src/layout/GlobalLayout.jsx
  frontend/src/pages/MainPage.jsx
  frontend/src/router.jsx
Labels: 🎨 프론트엔드, ✏️ 기능

#5 feat: 카카오 로그인 추가
  .github/workflows/frontend-prod-cd.yml
  backend/.yarn/install-state.gz
  backend/package.json
  backend/src/auth/auth.module.ts
  backend/src/auth/strategies/jwt.strategy.ts
  backend/src/game/game.controller.ts
  backend/src/game/game.module.ts
  backend/src/main.ts
  backend/yarn.lock
Labels: 💻 벡엔드, ✏️ 기능

#8 chore: swagger 설정 추가
  backend/package.json
  backend/src/auth/auth.service.ts
  backend/src/comment/comment.controller.ts
  backend/src/comment/comment.entity.ts
  backend/src/comment/comment.service.ts
  backend/src/comment/dto/comment.dto.ts
  backend/src/comment/dto/delete-comment.dto.ts
  backend/src/configs/setupSwagger.ts
  backend/src/game/game.controller.ts
  backend/src/item/item.controller.ts
  backend/src/item/item.entity.ts
  backend/src/main.ts
  backend/src/user/user.controller.ts
  backend/yarn.lock
  frontend/src/components/choice/Choice.jsx
  frontend/src/components/item/Item.styled.js
  frontend/src/pages/LoginAuthPage/LoginAuthPage.jsx
  frontend/src/pages/LoginPage/LoginPage.jsx
Labels: 💻 벡엔드, ✏️ 기능

#10 feat: best 댓글 가져오기 추가 및 comment에 user_id가 저장되지 않는 오류 수정
  backend/src/comment/comment.module.ts
  backend/src/comment/comment.service.ts
  backend/src/comment/dto/comment.dto.ts
  backend/src/item/item.controller.ts
  backend/src/item/item.module.ts
Labels: 🐛 버그, 💻 벡엔드, ✏️ 기능

#11 feat : CommentInput ui수정
  frontend/src/components/commentInput/CommentInput.styled.js
  frontend/src/components/comments/Comments.jsx
  frontend/src/components/comments/comment/Comment.styled.js
  frontend/src/components/common/icon/ArrowIcon.jsx
  frontend/src/pages/GamePage/GamePage.jsx
  frontend/src/pages/GamePage/GamePage.styled.js
Labels: 🎨 프론트엔드, ✏️ 기능

#16 feat : bestButtonColor 변경 추가
  frontend/src/components/choice/Choice.styled.js
  frontend/src/components/comments/Comments.jsx
  frontend/src/components/comments/Comments.styled.js
  frontend/src/components/comments/comment/Comment.jsx
  frontend/src/components/comments/comment/Comment.styled.js
  frontend/src/pages/GamePage/GamePage.jsx
  frontend/src/styles/theme.js
Labels: 🎨 프론트엔드, ✏️ 기능

#21 fix: 사용자 게임 불러오기 api dto 수정
  backend/src/game/dto/gameResponse.dto.ts
  backend/src/game/dto/gameUnit.dto.ts
  backend/src/game/game.controller.ts
  backend/src/game/game.service.ts
  frontend/src/context/UserInfoContext.jsx
Labels: 🐛 버그, 💻 벡엔드, ✏️ 기능

#23 feat: 댓글 삭제 api 추가 및 item isSelected 추가
  backend/src/comment/comment.controller.ts
  backend/src/comment/comment.service.ts
  backend/src/game/game.controller.ts
  backend/src/game/game.module.ts
  backend/src/game/game.service.ts
  backend/src/item/dto/item.dto.ts
  frontend/src/apis/deleteComment.js
  frontend/src/components/comments/comment/Comment.jsx
  frontend/src/constants/api.js
  frontend/src/hooks/queries/useDeleteComment.js
Labels: 🎨 프론트엔드, ✏️ 기능
